# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000
#   
# test:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000
# 
# production:
#   adapter: sqlite3
#   database: db/production.sqlite3
#   pool: 5
#   timeout: 5000

# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

# default: &defaults
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: root
#   password: 
#   host: localhost
# 
# development:
#   <<: *defaults
#   database: annotation_development
#   
# test: &test
#   <<: *defaults
#   database: annotation_test
  
# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

# default: &defaults
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: annotation
#   password: 
#   host: localhost
# 
# development:
#   <<: *defaults
#   database: annotation_development
#   
# test: &test
#   <<: *defaults
#   database: annotation_test